python scrape.py nasayi 5758 ../ihadith/
python scrape.py abi-dawud 5274 ../ihadith/
python scrape.py tirmidi 3956 ../ihadith/
python scrape.py ibn-majah 4341 ../ihadith/
python scrape.py muatta-malik 1832 ../ihadith/
python scrape.py riadus-saalehin 1905 ../ihadith/
python scrape.py bulugul-maram 1568 ../ihadith/
python scrape.py al-lulu-wal-marjan 1906 ../ihadith/
python scrape.py hadis-somvar 2013 ../ihadith/
python scrape.py silsila-sahiha 60 ../ihadith/
python scrape.py jal-daif-hadis-serise 102 ../ihadith/
python scrape.py mishkatul-masabih 2758 ../ihadith/
python scrape.py 40-hadis 42 ../ihadith/
python scrape.py adabul-mufrad 1336 ../ihadith/
python scrape.py juj-ul-rafaul-yadain 56 ../ihadith/
python scrape.py sahih-hadise-kudsi 163 ../ihadith/
python scrape.py 100-mashhur-hadis 101 ../ihadith/
python scrape.py daif-hadis-in-mishkat 106 ../ihadith/
python scrape.py shamayele-tirmidi 320 ../ihadith/
python scrape.py targib-wat-tahrib 200 ../ihadith/
python scrape.py sahih-fajayele-amal 151 ../ihadith/
python scrape.py upodesh 234 ../ihadith/
python scrape.py romjaner-durbol-hadis 36 ../ihadith/